name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:  # Allow manual triggering

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run cargo-fmt
        run: cargo fmt --all -- --check
      - name: Run cargo-clippy
        run: cargo clippy -- -D warnings
      - name: Check
        run: cargo check --verbose --workspace --all-targets

  # Tests for tpchgen
  test-tests-tpchgen:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v6
      - name: Tests (tpchgen)
        run: cargo test -p tpchgen --tests

  # doc examples test for tpchgen (takes a while)
  test-doc-tpchgen:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v6
      - name: Doc Tests (tpchgen)
        run: cargo test -p tpchgen --doc

  # All tests for tpchgen-arrow
  test-all-tpchgen-arrow:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v6
      - name: All Tests (tpchgen-arrow)
        run: cargo test -p tpchgen-arrow

  # All tests for tpchgen-cli
  test-all-tpchgen-cli:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v6
      - name: All Tests (tpchgen-cli)
        run: cargo test -p tpchgen-cli

  # All tests for tpcdsgen
  test-all-tpcdsgen:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v6
      - name: All Tests (tpcdsgen)
        run: cargo test -p tpcdsgen

  # documentation build
  docs:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v6
      - name : Build docs
        env:
          RUSTDOCFLAGS: "-D warnings"
        run: cargo doc --no-deps --workspace

  # Build wheels + sdist (but donâ€™t upload artifacts)
  build-packages:
    uses: ./.github/workflows/build-py-packages.yml
    with:
      upload-artifacts: false
